monolog:
  channels: ['google']
  handlers:
    main:
      type: stream
      path: '%kernel.logs_dir%/app.log'
      level: info

    # canal dédié aux appels de l'API Google
    google:
      type: stream
      path: '%kernel.logs_dir%/google.log'
      level: info
      channels: ['google']

    # en dev, loggue aussi en console (optionnel)
    console:
      type: console
      process_psr_3_messages: false
      channels: ['!event', '!doctrine', '!console']
